# Generated by Django 2.2.9 on 2022-08-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
