# Generated by Django 2.2.16 on 2022-08-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name'], 'verbose_name': 'Жанр'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name'], 'verbose_name': 'Произведение'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь'},
        ),
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', to='reviews.Genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
