# Generated by Django 2.2.16 on 2022-08-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='score',
            field=models.PositiveIntegerField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='GenresTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Genres', verbose_name='Жанр')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Titles', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Наименование и Жанр',
            },
        ),
    ]
