# Generated by Django 2.2.16 on 2022-08-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name'], 'verbose_name': 'Жанр'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['name'], 'verbose_name': 'Название'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.PositiveIntegerField(null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='reviews.Genres', verbose_name='Жанр произведения'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наменование'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='GenresTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Genres', verbose_name='Жанр')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Titles', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр и название',
            },
        ),
    ]
