# Generated by Django 2.2.16 on 2022-08-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220831_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrestitles',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genrestitles',
            old_name='title',
            new_name='title_id',
        ),
    ]
