# Generated by Django 2.2.16 on 2022-08-29 22:31

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220830_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(validators=[reviews.validators.current_year_validator], verbose_name='Год выпуска'),
        ),
    ]
