# Generated by Django 3.2.15 on 2022-08-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moderator',
        ),
    ]
