# Generated by Django 2.2.16 on 2022-09-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220906_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name']},
        ),
    ]
