# Generated by Django 2.2.16 on 2022-09-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220906_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
