# Generated by Django 2.2.16 on 2022-08-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220830_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
    ]
