# Generated by Django 3.2.15 on 2022-08-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verification',
            field=models.BooleanField(default=False),
        ),
    ]
