# Generated by Django 3.2.15 on 2022-08-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verification',
        ),
    ]
